"""empty message

Revision ID: d7135754e6a6
Revises: 9c08df3f3e32
Create Date: 2024-08-02 11:17:51.494757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7135754e6a6'
down_revision = '9c08df3f3e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('student2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student2', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
